# Documentation at http://goreleaser.com

# Project name
project_name: AINGLE

# Environment variables
env:
  - GO111MODULE=on

# Builds
builds:
  # Linux AMD64
  - id: aingle-linux-amd64
    binary: aingle
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X https://github.com/Ariwonto/aingle-alpha/plugins/cli.AppVersion={{.Version}}
    flags:
      - -tags=pow_avx
    main: main.go
    goos:
      - linux
    goarch:
      - amd64
  # Linux ARM64 statically linked
  - id: aingle-linux-arm64
    binary: aingle
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-musl-gcc
    ldflags:
      - -s -w -X https://github.com/Ariwonto/aingle-alpha/plugins/cli.AppVersion={{.Version}}
      - -w -extldflags "-static"
    flags:
      - -tags=pow_arm_c128
    main: main.go
    goos:
      - linux
    goarch:
      - arm64
  # Windows AMD64
  - id: aingle-windows-amd64
    binary: aingle
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    ldflags:
      - -s -w -X https://github.com/Ariwonto/aingle-alpha/plugins/cli.AppVersion={{.Version}}
    flags:
      - -tags=pow_avx
    main: main.go
    goos:
      - windows
    goarch:
      - amd64
  # macOS AMD64
  - id: aingle-macOS-amd64
    binary: aingle
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X https://github.com/Ariwonto/aingle-alpha/plugins/cli.AppVersion={{.Version}}
    main: main.go
    goos:
      - darwin
    goarch:
      - amd64

# Archives
archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}-{{.Version}}_{{.Os}}_{{.Arch}}"
    replacements:
      amd64: x86_64
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
      - README.md
      - LICENSE
      - config.json
      - config_comnet.json
      - config_devnet.json
      - peering.json
      - profiles.json
      - mqtt_config.json

# DEB and RPM packages
nfpms:
  - id: nfpm
    package_name: aingle
    file_name_template: '{{ tolower .ProjectName }}_{{ replace .Version "v" "" }}_{{ .Arch }}'
    vendor: GoReleaser
    license: Apache 2.0
    maintainer: iotaledger
    homepage: https://https://github.com/Ariwonto/aingle-alpha
    description: AINGLE is a powerful AINGLE fullnode software.
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    files:
      "nfpm/shared_files/aingle.service": "/lib/systemd/system/aingle.service"
    config_files:
      "config.json": "/var/lib/aingle/config.json"
      "config_comnet.json": "/var/lib/aingle/config_comnet.json"
      "config_devnet.json": "/var/lib/aingle/config_devnet.json"
      "mqtt_config.json": "/var/lib/aingle/mqtt_config.json"
      "peering.json": "/var/lib/aingle/peering.json"
      "profiles.json": "/var/lib/aingle/profiles.json"
      "nfpm/shared_files/aingle.env": "/etc/default/aingle"
    dependencies:
      - systemd
      - wget
      - bash
    scripts:
      preremove: "nfpm/deb_files/prerm"
      postremove: "nfpm/deb_files/postrm"
      preinstall: "nfpm/deb_files/preinst"
      postinstall: "nfpm/deb_files/postinst"
    overrides:
      rpm:
        replacements:
          amd64: x86_64
        file_name_template: "{{ tolower .ProjectName }}-{{ .Version }}-{{ .Arch }}"
        scripts:
          preinstall: "nfpm/rpm_files/preinst"
          postinstall: "nfpm/rpm_files/postinst"
          preremove: "nfpm/rpm_files/prerm"
          postremove: "nfpm/rpm_files/postrm"

# Checksum
checksum:
  name_template: "checksums.txt"

# Snapshot
snapshot:
  name_template: "{{ .Tag }}"

# Changelog
changelog:
  skip: true

# Release
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-{{.Version}}"
  github:
    owner: iotaledger
    name: aingle
