#!/bin/sh
set -e

case "$1" in
configure)

	chown -R aingle:aingle /var/lib/aingle

	if type systemctl >/dev/null 2>/dev/null; then
		systemctl daemon-reload

		# Only restart if the AINGLE service is enabled
		if systemctl is-enabled -q aingle.service; then
			systemctl --no-block restart aingle.service
		fi

	fi
	;;

abort-upgrade | abort-remove | abort-deconfigure) ;;

*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
